notify = [
  "terminal-notifier",
  "-message", "done",
  "-sound", "Bell"
]

model = "gpt-5.3-codex" 
model_provider = "azure"
model_reasoning_effort = "medium"
model_reasoning_summary = "auto"
model_verbosity = "medium"
model_supports_reasoning_summaries = true

approval_policy = "on-request"
sandbox_mode = "danger-full-access"
disable_response_storage = false
personality = "pragmatic"

[shell_environment_policy]
inherit = "all"

ignore_default_excludes = false
exclude = ["AWS_*", "AZURE_*"]
set = { }
include_only = []

[model_providers.azure]
name = "Azure OpenAI"
base_url = "https://dev-atrium-eastus2-1.openai.azure.com/openai/v1"
env_key = "AZURE_DEV_OPENAI_API_KEY"
wire_api = "responses"

[features]
shell_snapshot = true
unified_exec = true
steer = true
personality = true
multi_agent = true
prevent_idle_sleep = true
