font_size 16.0
hide_window_decorations titlebar-and-corners


# BEGIN_KITTY_THEME
# Nord
include current-theme.conf
# END_KITTY_THEME

map ctrl+tab send_text all \x1b[9;5u # <c-tab>

# Enable remote control for precise window focus
allow_remote_control yes
listen_on unix:/tmp/kitty
