[tools]
node = "latest"
yarn = "1.22.22"
lua = "5.1"
watchexec = "latest"
python = "latest"
pipx = "latest"

[env]
_.file = '~/.config/mise/secrets.env'
LOCAL_DB="postgresql://postgres:root@localhost/enterprise_gpt_api"
DB_UI_LOCAL="postgresql://postgres:root@localhost/enterprise_gpt_api"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
